Basketbool.Web/Models/MatchDayDetailViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Basketbool.Web.Data.Entities;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Basketbool.Web.Models
{
    public class MatchDayDetailViewModel : MatchDayDetailEntity
    {
        public int MatchDayId { get; set; }

        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Team")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a team.")]
        public int TeamId { get; set; }

        public IEnumerable<SelectListItem> Teams { get; set; }

    }
}

Basketbool.Web/Models/MatchViewModel.cs
using Basketbool.Web.Data.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Basketbool.Web.Models
{
    public class MatchViewModel : MatchEntity
    {
        public int MatchDayId { get; set; }

        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Local")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a team.")]
        public int LocalId { get; set; }

        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Visitor")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a team.")]
        public int VisitorId { get; set; }

        public IEnumerable<SelectListItem> Teams { get; set; }

    }
}

Basketbool.Web/Models/TeamViewModel.cs
using Basketbool.Web.Data.Entities;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace Basketbool.Web.Models
{
    public class TeamViewModel : TeamEntity
    {

        [Display(Name = "Logo")]
        public IFormFile LogoFile { get; set; }

    }
}

Basketbool.Web/Controllers/SeasonsController.cs
using Basketbool.Web.Data;
using Basketbool.Web.Data.Entities;
using Basketbool.Web.Interfaces;
using Basketbool.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Basketbool.Web.Controllers
{
    public class SeasonsController : Controller
    {
        private readonly DataContext _context;
        private readonly IConverterHelper _converterHelper;
        private readonly ICombosHelper _combosHelper;

        public SeasonsController(DataContext context, 
            IConverterHelper converterHelper,
            ICombosHelper combosHelper)
        {
            _context = context;
            _converterHelper = converterHelper;
            _combosHelper = combosHelper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context
                .Seasons
                .Include(t => t.MatchDays)
                .OrderBy(t => t.StartDate)
                .ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SeasonEntity model)
        {
            if (ModelState.IsValid)
            {
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SeasonEntity seasonEntity = await _context.Seasons.FindAsync(id);
            if (seasonEntity == null)
            {
                return NotFound();
            }

            return View(seasonEntity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SeasonEntity model)
        {
            if (ModelState.IsValid)
            {
                _context.Update(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SeasonEntity seasonEntity = await _context.Seasons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (seasonEntity == null)
            {
                return NotFound();
            }

            _context.Seasons.Remove(seasonEntity);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SeasonEntity seasonEntity = await _context.Seasons
                .Include(t => t.MatchDays)
                .ThenInclude(t => t.Matches)
                .ThenInclude(t => t.Local)
                .Include(t => t.MatchDays)
                .ThenInclude(t => t.Matches)
                .ThenInclude(t => t.Visitor)
                .Include(t => t.MatchDays)
                .ThenInclude(t => t.MatchDayDetails)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (seasonEntity == null)
            {
                return NotFound();
            }

            return View(seasonEntity);
        }

        public async Task<IActionResult> AddMatchDay(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SeasonEntity seasonEntity = await _context.Seasons.FindAsync(id);
            if (seasonEntity == null)
            {
                return NotFound();
            }

            MatchDayViewModel model = new MatchDayViewModel
            {
                Season = seasonEntity,
                SeasonId = seasonEntity.Id
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMatchDay(MatchDayViewModel model)
        {
            if (ModelState.IsValid)
            {
                MatchDayEntity matchDayEntity = await _converterHelper.ToMatchDayEntityAsync(model, true);
                _context.Add(matchDayEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction($"{nameof(Details)}", new { id = model.SeasonId });
            }

            return View(model);
        }

        public async Task<IActionResult> EditMatchDay(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            MatchDayEntity matchDayEntity = await _context.MatchDays
                .Include(g => g.Season)
                .FirstOrDefaultAsync(g => g.Id == id);
            if (matchDayEntity == null)
            {
                return NotFound();
            }

            MatchDayViewModel model = _converterHelper.ToMatchDayViewModel(matchDayEntity);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditMatchDay(MatchDayViewModel model)
        {
            if (ModelState.IsValid)
            {
                MatchDayEntity matchDayEntity = await _converterHelper.ToMatchDayEntityAsync(model, false);
                _context.Update(matchDayEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction($"{nameof(Details)}", new { id = model.SeasonId });
            }

            return View(model);
        }

        public async Task<IActionResult> DeleteMatchDay(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            MatchDayEntity matchDayEntity = await _context.MatchDays
                .Include(g => g.Season)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (matchDayEntity == null)
            {
                return NotFound();
            }

            _context.MatchDays.Remove(matchDayEntity);
            await _context.SaveChangesAsync();
            return RedirectToAction($"{nameof(Details)}", new { id = matchDayEntity.Season.Id });
        }

        public async Task<IActionResult> DetailsMatchDay(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            MatchDayEntity matchDayEntity = await _context.MatchDays
                .Include(g => g.Matches)
                .ThenInclude(g => g.Local)
                .Include(g => g.Matches)
                .ThenInclude(g => g.Visitor)
                .Include(g => g.Season)
                .Include(g => g.MatchDayDetails)
                .ThenInclude(gd => gd.Team)
                .FirstOrDefaultAsync(g => g.Id == id);
            if (matchDayEntity == null)
            {
                return NotFound();
            }

            return View(matchDayEntity);
        }

        public async Task<IActionResult> AddMatchDayDetail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            MatchDayEntity matchDay = await _context.MatchDays.FindAsync(id);
            if (matchDay == null)
            {
                return NotFound();
            }

            MatchDayDetailViewModel model = new MatchDayDetailViewModel
            {
                MatchDay = matchDay,
                MatchDayId = matchDay.Id,
                Teams = _combosHelper.GetComboTeams()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMatchDayDetail(MatchDayDetailViewModel model)
        {
            if (ModelState.IsValid)
            {
                MatchDayDetailEntity matchDayDetailEntity = await _converterHelper.ToMatchDayDetailEntityAsync(model, true);
                _context.Add(matchDayDetailEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction($"{nameof(DetailsMatchDay)}", new { id = model.MatchDayId });
            }

            model.MatchDay = await _context.MatchDays.FindAsync(model.MatchDayId);
            model.Teams = _combosHelper.GetComboTeams();
            return View(model);
        }

        public async Task<IActionResult> AddMatch(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            MatchDayEntity matchDayEntity = await _context.MatchDays.FindAsync(id);
            if (matchDayEntity == null)
            {
                return NotFound();
            }

            MatchViewModel model = new MatchViewModel
            {
                Date = DateTime.Today,
                MatchDay = matchDayEntity,
                MatchDayId = matchDayEntity.Id,
                Teams = _combosHelper.GetComboTeams(matchDayEntity.Id)
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMatch(MatchViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.LocalId != model.VisitorId)
                {
                    MatchEntity matchEntity = await _converterHelper.ToMatchEntityAsync(model, true);
                    _context.Add(matchEntity);
                    await _context.SaveChangesAsync();
                    return RedirectToAction($"{nameof(DetailsMatchDay)}", new { id = model.MatchDayId });
                }

                ModelState.AddModelError(string.Empty, "The local and visitor must be differents teams.");
            }

Basketbool.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using Basketbool.Web.Common;
using Basketbool.Web.Data;
using Basketbool.Web.Data.Entities;
using Basketbool.Web.Enums;
using Basketbool.Web.Interfaces;
using Basketbool.Web.Models;

namespace Basketbool.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserHelper _userHelper;
        private readonly DataContext _context;
        private readonly ICombosHelper _combosHelper;
        private readonly IBlobHelper _blobHelper;
        private readonly IMailHelper _mailHelper;
        public UsersController(IUserHelper userHelper,
            DataContext context,
            ICombosHelper combosHelper,
            IBlobHelper blobHelper,
            IMailHelper mailHelper)
        {
            _userHelper = userHelper;
            _context = context;
            _combosHelper = combosHelper;
            _blobHelper = blobHelper;
            _mailHelper = mailHelper;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users
            //.Include(u => u.City)
            //.ThenInclude(c => c.Department)
            //.ThenInclude(s => s.Country)
            .ToListAsync());

        }
        public async Task<IActionResult> Create()
        {
            AddUserViewModel model = new AddUserViewModel
            {
                Id = Guid.Empty.ToString(),
                //Countries = await _combosHelper.GetComboCountriesAsync(),
                //Departments = await _combosHelper.GetComboDepartmentsAsync(1),
                //Cities = await _combosHelper.GetComboCitiesAsync(1),
                //UserType = UserType.Admin,
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                Guid imageId = Guid.Empty;
                // if (model.ImageFile != null)
                // {
                //     imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "users");
                // }
                UserEntity user = await _userHelper.AddUserAsync(model, imageId);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "Este correo ya está siendo usado.");
                    return View(model);
                }
                string myToken = await _userHelper.GenerateEmailConfirmationTokenAsync(user);
                string tokenLink = Url.Action("ConfirmEmail", "Account", new
                {
                    userid = user.Id,
                    token = myToken
                }, protocol: HttpContext.Request.Scheme);
                Response response = _mailHelper.SendMail(
                $"{model.FirstName} {model.LastName}",
                model.Username,
                "Shopping - Confirmación de Email",
                $"<h1>Shopping - Confirmación de Email</h1>" +
                $"Para habilitar el usuario por favor hacer clicn en el siguiente link:, " +
                $"<p><a href = \"{tokenLink}\">Confirmar Email</a></p>");
                if (response.IsSuccess)
                {
                    ViewBag.Message = "Las instrucciones para habilitar el usuario han sido enviadas al correo.";
                    return View(model);
                }
                ModelState.AddModelError(string.Empty, response.Message);

            }
            return View(model);
        }
        //public JsonResult? GetDepartments(int countryId)
        //{
        //    Country? country = _context.Countries
        //    .Include(c => c.Departments)
        //    .FirstOrDefault(c => c.Id == countryId);
        //    if (country == null)
        //    {
        //        return null;
        //    }
        //    return Json(country.Departments.OrderBy(d => d.Name));

        //}
        //public JsonResult? GetCities(int DepartmentId)
        //{
        //    Department? Department = _context.Departments
        //    .Include(s => s.Cities)
        //    .FirstOrDefault(s => s.Id == DepartmentId);
        //    if (Department == null)
        //    {
        //        return null;
        //    }
        //    return Json(Department.Cities.OrderBy(c => c.Name));
        //}
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(new LoginViewModel());
        }
    }

}

Basketbool.Web/Views/Shared/_DeleteDialog.cshtml
<div class="modal fade" id="deleteDialog" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

    <div class="modal-dialog" role="document">

        <div class="modal-content">

            <div class="modal-header">

                <h5 class="modal-title" id="exampleModalLabel">Delete Record</h5>

            </div>

            <div class="modal-body">

                <p>Are you sure to wanto to delete the record?</p>

            </div>

            <div class="modal-footer">

                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>

                <button type="button" class="btn btn-danger" id="btnYesDelete">Yes</button>

            </div>

        </div>

    </div>

</div>s

Basketbool.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Basketbool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Basketbool.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fa-solid fa-basketball text-white"></i> Basketbool
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Teams" asp-action="Index">Teams</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Seasons" asp-action="Index">Seasons</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Index">Usuarios</a>
                            </li>
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="ChangeUser">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Logout">Cerrar Sesión</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Iniciar Sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Basketbool.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/fontawesome.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Basketbool.Web/Views/Shared/_Match.cshtml
@model Basketbool.Web.Models.MatchViewModel

<div class="form-group">
    <label asp-for="Date" class="control-label"></label>
    <input asp-for="Date" class="form-control" />
    <span asp-validation-for="Date" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="LocalId" class="control-label"></label>
    <select asp-for="LocalId" asp-items="Model.Teams" class="form-control"></select>
    <span asp-validation-for="LocalId" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="VisitorId" class="control-label"></label>
    <select asp-for="VisitorId" asp-items="Model.Teams" class="form-control"></select>
    <span asp-validation-for="VisitorId" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PointsLocal" class="control-label"></label>
    <input asp-for="PointsLocal" class="form-control" />
    <span asp-validation-for="PointsLocal" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PointsVisitor" class="control-label"></label>
    <input asp-for="PointsVisitor" class="form-control" />
    <span asp-validation-for="PointsVisitor" class="text-danger"></span>
</div>

<div class="form-group">
    <div class="checkbox">
        <label>
            <input asp-for="IsClosed" /> @Html.DisplayNameFor(model => model.IsClosed)
        </label>
    </div>
</div>

Basketbool.Web/Views/Shared/_MatchDay.cshtml
@model Basketbool.Web.Models.MatchDayViewModel

<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Basketbool.Web/Views/Shared/_MatchDayDetail.cshtml
@model Basketbool.Web.Models.MatchDayDetailViewModel

<div class="form-group">
    <label asp-for="TeamId" class="control-label"></label>
    <select asp-for="TeamId" asp-items="Model.Teams" class="form-control"></select>
    <span asp-validation-for="TeamId" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="MatchesPlayed" class="control-label"></label>
    <input asp-for="MatchesPlayed" class="form-control" />
    <span asp-validation-for="MatchesPlayed" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="MatchesWon" class="control-label"></label>
    <input asp-for="MatchesWon" class="form-control" />
    <span asp-validation-for="MatchesWon" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="MatchesTied" class="control-label"></label>
    <input asp-for="MatchesTied" class="form-control" />
    <span asp-validation-for="MatchesTied" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="MatchesLost" class="control-label"></label>
    <input asp-for="MatchesLost" class="form-control" />
    <span asp-validation-for="MatchesLost" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PointsFor" class="control-label"></label>
    <input asp-for="PointsFor" class="form-control" />
    <span asp-validation-for="PointsFor" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PointsAgainst" class="control-label"></label>
    <input asp-for="PointsAgainst" class="form-control" />
    <span asp-validation-for="PointsAgainst" class="text-danger"></span>
</div>

Basketbool.Web/Views/Shared/_Season.cshtml
@model Basketbool.Web.Data.Entities.SeasonEntity

<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="StartDate" class="control-label"></label>
    <input asp-for="StartDate" class="form-control" />
    <span asp-validation-for="StartDate" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="EndDate" class="control-label"></label>
    <input asp-for="EndDate" class="form-control" />
    <span asp-validation-for="EndDate" class="text-danger"></span>
</div>

<div class="form-group">
    <div class="checkbox">
        <label>
            <input asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
        </label>
    </div>
</div>

Basketbool.Web/Views/Shared/_Team.cshtml
@model Basketbool.Web.Models.TeamViewModel

<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="LogoFile" class="control-label"></label>
    <input asp-for="LogoFile" type="file" class="form-control" />
    <span asp-validation-for="LogoFile" class="text-danger"></span>
</div>

Basketbool.Web/Views/Shared/_User.cshtml
@model Basketbool.Web.Models.EditUserViewModel

<div class="form-group">
    <label asp-for="Document" class="control-label"></label>
    <input asp-for="Document" class="form-control" />
    <span asp-validation-for="Document" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="FirstName" class="control-label"></label>
    <input asp-for="FirstName" class="form-control" />
    <span asp-validation-for="FirstName" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="LastName" class="control-label"></label>
    <input asp-for="LastName" class="form-control" />
    <span asp-validation-for="LastName" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Address" class="control-label"></label>
    <input asp-for="Address" class="form-control" />
    <span asp-validation-for="Address" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PhoneNumber" class="control-label"></label>
    <input asp-for="PhoneNumber" class="form-control" />
    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="ImageFile" class="control-label"></label>
    <input asp-for="ImageFile" class="form-control" type="file" />
    <span asp-validation-for="ImageFile" class="text-danger"></span>
</div>

@*<div class="form-group">
    <label asp-for="CountryId" class="control-label"></label>
    <select asp-for="CountryId" asp-items="Model.Countries" class="form-control"></select>
    <span asp-validation-for="CountryId" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="DepartmentId" class="control-label"></label>
    <select asp-for="DepartmentId" asp-items="Model.Departments" class="form-control"></select>
    <span asp-validation-for="DepartmentId" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="CityId" class="control-label"></label>
    <select asp-for="CityId" asp-items="Model.Cities" class="form-control"></select>
    <span asp-validation-for="CityId" class="text-danger"></span>
</div>*@